// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtjdbcWiEoo1NSkwMR8prEjsxJ9ZTLJWw',
    appId: '1:615712209466:web:2264b8cf875dba2944d303',
    messagingSenderId: '615712209466',
    projectId: 'my-watchlist-7213b',
    authDomain: 'my-watchlist-7213b.firebaseapp.com',
    storageBucket: 'my-watchlist-7213b.firebasestorage.app',
    measurementId: 'G-JY4YDS6H1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh17dCHt8y5hEvyckNBopaPRSKxwQM4hc',
    appId: '1:615712209466:android:15fd2da6cc4e7cb544d303',
    messagingSenderId: '615712209466',
    projectId: 'my-watchlist-7213b',
    storageBucket: 'my-watchlist-7213b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6kL46V7fpIcDdAMUfrYkzPhbQI0IyeWg',
    appId: '1:615712209466:ios:6f83f43eb6173bbf44d303',
    messagingSenderId: '615712209466',
    projectId: 'my-watchlist-7213b',
    storageBucket: 'my-watchlist-7213b.firebasestorage.app',
    iosBundleId: 'com.example.movieWatchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6kL46V7fpIcDdAMUfrYkzPhbQI0IyeWg',
    appId: '1:615712209466:ios:6f83f43eb6173bbf44d303',
    messagingSenderId: '615712209466',
    projectId: 'my-watchlist-7213b',
    storageBucket: 'my-watchlist-7213b.firebasestorage.app',
    iosBundleId: 'com.example.movieWatchlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtjdbcWiEoo1NSkwMR8prEjsxJ9ZTLJWw',
    appId: '1:615712209466:web:7645c066683ed80244d303',
    messagingSenderId: '615712209466',
    projectId: 'my-watchlist-7213b',
    authDomain: 'my-watchlist-7213b.firebaseapp.com',
    storageBucket: 'my-watchlist-7213b.firebasestorage.app',
    measurementId: 'G-80J484TR52',
  );
}
